import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const webpackCompatScript = `
(function () {
  if (typeof window === "undefined") return;
  function ensureInteropHelper() {
    if (typeof __webpack_require__ === "function" && typeof __webpack_require__.n !== "function") {
      __webpack_require__.n = function (module) {
        var getter = module && module.__esModule ? function () { return module.default; } : function () { return module; };
        getter.a = getter;
        return getter;
      };
    }
  }
  ensureInteropHelper();
  if (typeof __webpack_require__ !== "function" || typeof __webpack_require__.n !== "function") {
    var attempts = 0;
    var interval = setInterval(function () {
      ensureInteropHelper();
      attempts += 1;
      if ((typeof __webpack_require__ === "function" && typeof __webpack_require__.n === "function") || attempts > 300) {
        clearInterval(interval);
      }
    }, 10);
    window.addEventListener("load", function () {
      ensureInteropHelper();
      clearInterval(interval);
    }, { once: true });
  }
})();
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="webpack-interop-polyfill" strategy="beforeInteractive">
          {webpackCompatScript}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
